name: daily-devcard
on:
  # Run manually from the Actions tab
  workflow_dispatch:
  push:
    # Run any time this branch is modified
    branches:
      - main
  schedule: # Execute every 24 hours
    - cron: "0 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.2.1
        with:
          user_id: ${{ secrets.USER_ID }}
          type: wide
          commit_message: "Update ${filename}"
