name: Update weekly streak stats

on:
  schedule:
    - cron: "0 3 * * *" # Run every day at 03:00
  push:
    paths:
      - ".github/workflows/weekly-streak-stats.yml" # Run any time this file is modified
  workflow_dispatch: # Run manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Generate weekly streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&mode=weekly&theme=chartreuse-dark
          path: profile/weekly-streak.svg
          token: ${{ secrets.STREAK_STATS_GITHUB_TOKEN }}

      - name: Commit weekly streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/weekly-streak.svg
          git commit -m "Update weekly streak stats" || exit 0
          git pull --rebase origin main
          git push
